# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  enabled: true
  host: 0.0.0.0
  port: 8548

development:
  <<: *default

test:
  <<: *default
  enabled: false

production:
  <<: *default
  enabled: false
